namespace Controleo.Infrastructure.Persistence;
internal sealed class ExpenseDocument { public string Id { get; set; } = ""; public string UserId { get; set; } = ""; public string Date { get; set; } = ""; public string MonthKey { get; set; } = ""; public string Description { get; set; } = ""; public decimal Amount { get; set; } public string MovementType { get; set; } = ""; public string PaymentMethod { get; set; } = ""; public bool IsCredit { get; set; } public int? Installments { get; set; } public string? ClientMutationId { get; set; } public string? SourceRecurringId { get; set; } public string? SourceRecurringMonth { get; set; } public string CreatedAt { get; set; } = ""; public string UpdatedAt { get; set; } = ""; }
internal sealed class BudgetDocument { public string Id { get; set; } = ""; public string UserId { get; set; } = ""; public string MovementType { get; set; } = ""; public decimal Amount { get; set; } public string UpdatedAt { get; set; } = ""; }
internal sealed class CatalogDocument { public string Id { get; set; } = ""; public string UserId { get; set; } = ""; public string[] MovementTypes { get; set; } = []; public string[] PaymentMethods { get; set; } = []; public MovementTypeConfigDoc[] MovementTypeConfigs { get; set; } = []; public PaymentMethodConfigDoc[] PaymentMethodConfigs { get; set; } = []; public string UpdatedAt { get; set; } = ""; }
internal sealed class MovementTypeConfigDoc { public string Name { get; set; } = ""; public string Icon { get; set; } = ""; public string Color { get; set; } = ""; }
internal sealed class PaymentMethodConfigDoc { public string Name { get; set; } = ""; public string Icon { get; set; } = ""; public bool IsCredit { get; set; } public int? DefaultInstallments { get; set; } public int? DueDayOfMonth { get; set; } public int? ReminderDaysBefore { get; set; } }
internal sealed class RecurringExpenseDocument { public string Id { get; set; } = ""; public string UserId { get; set; } = ""; public string Description { get; set; } = ""; public decimal Amount { get; set; } public string MovementType { get; set; } = ""; public string PaymentMethod { get; set; } = ""; public int DayOfMonth { get; set; } public string StartMonth { get; set; } = ""; public string? EndMonth { get; set; } public bool IsActive { get; set; } public string CreatedAt { get; set; } = ""; public string UpdatedAt { get; set; } = ""; }
internal sealed class ObligationDocument { public string Id { get; set; } = ""; public string UserId { get; set; } = ""; public string DocType { get; set; } = "obligation"; public string Description { get; set; } = ""; public string MovementType { get; set; } = ""; public string PaymentMethod { get; set; } = ""; public int DueDayOfMonth { get; set; } public decimal MonthlyPayment { get; set; } public int ReminderDaysBefore { get; set; } public string StartMonth { get; set; } = ""; public bool IsActive { get; set; } = true; public string CreatedAt { get; set; } = ""; public string UpdatedAt { get; set; } = ""; }
internal sealed class ExpenseMonthProjection { public string? MonthKey { get; set; } public string? Date { get; set; } }
internal sealed class ExpenseIdentity { public string? Id { get; set; } }
internal sealed class BudgetIdentity { public string? Id { get; set; } public string? MovementType { get; set; } }
internal sealed class IdentityPartitionRow { public string? Id { get; set; } public string? PartitionKey { get; set; } }
